language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"

before_install:
    - sudo apt-get update
    - sudo apt-get install libhdf5-serial-dev #hdf5-tools

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
#    - pip install cython  #not a h5py dependency
    - pip install numpy
    - pip install h5py

#before_script:
#    - chmod +x do_nothing.sh

# # command to run tests, e.g. python setup.py test
script:
    - "python run_tests.py"

notifications:
  email: false
